apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
