apiVersion: v1
kind: Service
metadata:
  name: svc-mybudget-api
spec:
  type: NodePort
  ports:
    - port: 8081        # Porta do container
      targetPort: 8081  # Porta exposta pelo serviço
      nodePort: 30081   # Porta exposta externamente
  selector:
    app: mybudget-api
