apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
