apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 8080        # Porta do container
      targetPort: 8080  # Porta exposta pelo serviço
      nodePort: 30080   # Porta exposta externamente
  selector:
    app: frontend
